name: "test"
on: ["push"]
jobs:
  setup-environment:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Create conda environment"
        run: "conda init && conda env create"

  test:
    needs: "setup-environment"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Run static analysis / tests"
        run: "conda activate cryo-data-ingest && inv test.ci"
